[package]
name = "nvapi"
version = "0.2.1" # keep in sync with html_root_url
authors = ["arcnmx"]
edition = "2021"

description = "NVIDIA NVAPI bindings"
keywords = ["nvidia", "nvapi", "gtx"]

documentation = "https://docs.rs/nvapi/latest/nvapi/"
repository = "https://github.com/arcnmx/nvapi-rs"
readme = "README.md"
license = "MIT"

[dependencies]
nvapi-sys = { version = "^0.2.0", path = "sys", default-features = false }
serde = { version = "^1.0.0", optional = true }
serde_derive = { version = "^1.0.0", optional = true }
i2c = { version = "^0.1.0", optional = true }
log = "^0.4.1"

[features]
serde_types = ["serde", "serde_derive", "nvapi-sys/serde_types"]
default = ["serde_types"]

[workspace]
members = ["sys", "hi"]
